[project]
name = "hello-world"
version = "0.1.0"
description = "FastAPI app for Coolify running on port 5001"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
